import { Translations } from '../types'

const en: Translations = {
  common: {
    continue: 'Continue',
    confirm: 'Confirm',
    cancel: 'Cancel',
    back: 'Back',
    next: 'Next',
    players: 'Players',
    player: 'Player',
    roles: 'Roles',
    role: 'Role',
    random: 'Random',
    startGame: 'Start Game',
    mainMenu: 'Main Menu',
    history: 'History',
    notes: 'Notes',
    winCondition: 'Win Condition',
    youAreThe: 'You are the...',
    iUnderstandMyRole: 'I understand my role',
  },

  mainMenu: {
    title: 'Grimorium',
    subtitle: 'Every Storyteller needs a Grimoire.',
    tapToOpen: 'Tap to open',
    continueGame: 'Continue Game',
    newGame: 'New Game',
    startFreshGame: 'Start a fresh game',
    rolesLibrary: 'Roles Library',
    browseAllRoles: 'Browse all role cards',
    previousGames: 'Previous Games',
    completed: 'Completed',
    settingUp: 'Setting up',
    round: 'Round',
    language: 'Language',
  },

  newGame: {
    step1Title: 'New Game',
    step1Subtitle: 'Step 1: Set player count',
    addPlayer: 'Add Player',
    playerPlaceholder: 'Player',
    playerCountLabel: 'Total Players',
    playerCountHelp:
      'Choose how many players are in the game. The Storyteller is not included.',
    recommendedSplit: 'Recommended Team Split',
    seatsAutoGenerated:
      'Seat labels are generated automatically for now and can be refined in a later pass.',
    roleDrawTitle: 'Deal Roles',
    roleDrawSubtitle:
      'Step 3: Reveal a random role and capture each player name',
    roleDrawHelp:
      'Hand the device around the circle. Each player taps a card, privately sees their role, then enters their name to lock it in.',
    rolesDealtLabel: 'roles dealt',
    regenerateDeck: 'Regenerate',
    tapToRevealRole: 'Tap to reveal',
    drunkSetupTitle: 'Drunk Setup',
    drunkSetupSubtitle:
      'Choose the believed Townsfolk role before any player reveals',
    drunkSetupDescription:
      'This bag contains the Drunk. Pick which Townsfolk character that player should believe they are, then continue with the normal reveal flow.',
    chooseBelievedRole: 'Choose the believed Townsfolk role',
    playerNameLabel: 'Player Name',
    playerNamePlaceholder: 'Enter player name',
    lockRoleAndName: 'Lock role and name',
    roleLockedLabel: 'Role locked in',
    minPlayersWarning: 'Add at least 5 players to continue',
    nextSelectRoles: 'Next: Select Roles',
    loadedFromLastGame: 'From last game',

    step2Title: 'New Game',
    step2Subtitle: 'Step 2: Select roles in play',
    needAtLeastRoles: 'Need at least {count} roles',
    needAtLeastImp: 'Need at least 1 Imp',
    needAtLeastDemon: 'Need at least 1 Demon',
    nextAssignRoles: 'Next: Assign Roles',
    suggested: 'Suggested',

    step3Title: 'New Game',
    step3Subtitle: 'Step 3: Assign roles (optional)',
    assignmentInfo:
      'Optionally assign specific roles to players. Unassigned players get random roles from the pool.',
    resetToRandom: 'Reset all to random',
    playerAssignments: 'Player Assignments',
    randomPool: 'Random Pool',
    rolesForPlayers: '{roles} roles for {players} players',
    impNotAssignedWarning:
      "The Imp won't be assigned! Make sure at least one player gets the Imp or leave some players random.",
    demonNotAssignedWarning:
      "A Demon won't be assigned! Make sure at least one player gets a Demon or leave some players random.",
    rolesRandomlyAssigned: 'Roles will be randomly assigned to players',
    customizeAssignments: 'Customize Assignments',
    tapToAssign: 'Tap a player to assign a specific role',
  },

  game: {
    narratorGiveDevice: 'Give the device to {player} to see their role.',
    narratorWakePlayer: 'Wake {player} ({role}) for their night action.',
    narratorRoleChanged:
      'Give the device to {player} — their role has changed.',
    readyShowToPlayer: 'Ready - Show to Player',
    yourRoleHasChanged: 'Your role has changed!',
    yourGoodTwinIs: 'Your good twin is...',
    yourEvilTwinIs: 'Your evil twin is...',

    nightComplete: 'Night {round} Complete',
    nightActionsResolved:
      'All night actions have been resolved. Ready to start the day?',
    startDay: 'Start Day',
    choosePlayerToKill: 'Choose a player to kill',
    selectVictim:
      'Select the player they pointed to as their victim for tonight.',
    confirmKill: 'Confirm Kill',

    grimoire: 'Grimoire',
    daytimeActions: 'Daytime Actions',
    accusePlayerDescription: 'Accuse a player and put them to vote',

    nominatesForExecution: '{nominator} nominates {nominee} for execution',
    nominatesVerb: 'nominates',
    forExecution: 'for execution',

    day: 'Day',
    discussionAndNominations: 'Discussion and nominations',
    alivePlayersLabel: 'Alive',
    blockThresholdLabel: 'To block',
    newNomination: 'New Nomination',
    whoIsNominating: 'Who is nominating?',
    whoAreTheyNominating: 'Who are they nominating?',
    selectNominator: 'Select nominator...',
    selectNominee: 'Select nominee...',
    startNomination: 'Start Nomination',

    executePlayer: 'Vote on {player}',
    votesNeeded: '{count} votes needed',
    votesCount: 'Votes',
    voteThreshold: 'of {threshold} needed',
    voteAction: 'Vote',
    dontVote: "Don't Vote",
    goesOnBlock: '{player} goes on the block!',
    notEnoughVotes: 'Not enough votes',
    tiedNoExecution: 'Tied \u2014 no execution',
    currentBlock: '{player} on the block ({count} votes)',
    needMoreThan: 'Need more than {count} to replace',
    noOneOnBlock: 'No one on the block',
    endDayExecute: 'End Day \u2014 Execute {player}',
    endDayNoExecution: 'End Day \u2014 No Execution',
    confirmVotes: 'Confirm Votes',
    cancelNomination: 'Cancel Nomination',
    nominee: 'Nominee',
    ghostVoteAvailable: 'Ghost vote available',
    ghostVoteSpent: 'Ghost vote spent',
    cannotVote: 'Cannot vote',
    butlerCannotVote: 'Cannot vote unless master votes',
    butlerDeadWarning: 'Master rule does not apply while dead',

    // Slayer
    slayerAction: 'Slayer Shot',
    slayerActionDescription: 'Claim to be the Slayer and shoot a player',
    selectSlayer: 'Select Slayer',
    selectTarget: 'Select Target',
    confirmSlayerShot: 'Confirm Shot',

    goodWins: 'Good Wins!',
    evilWins: 'Evil Wins!',
    townVanquishedDemon: 'The town has vanquished the Demon!',
    demonConqueredTown: 'The Demon has conquered the town!',
    winTriggeredBy: 'Win Trigger',
    winReasonAllDemonsDead: 'All Demons are dead.',
    winReasonFinalTwoAlive:
      'Only 2 players are alive and at least 1 is a Demon.',
    winReasonVortoxNoExecution:
      'Vortox rule: no execution happened today.',
    winReasonMartyrdomExecution:
      'Execution triggered a martyrdom-style evil win condition.',
    winReasonEvilTwinGoodExecuted:
      'Good Twin was executed.',
    winReasonEvilTwinEvilExecuted:
      'Evil Twin was executed.',
    winReasonMayorPeacefulVictory:
      'Mayor peaceful-victory condition was met.',
    winReasonSpecialAbility:
      'A special ability win condition was met.',
    winReasonSourceRole: 'Source role: {role}',
    winReasonSourceEffect: 'Source effect: {effect}',
    finalRoles: 'Final Roles',
    backToMainMenu: 'Back to Main Menu',

    gameHistory: 'Game History',
    storytellerMenu: 'Storyteller Menu',
    showGrimoire: 'Show Grimoire',
    showAllCharacters: 'Show All Characters',
    takeNotes: 'Take Notes',
    storytellerNotes: 'Storyteller Notes',
    storytellerNotesDescription:
      'Keep quick reminders, claims, and suspicions while you run the game.',
    storytellerNotesPlaceholder:
      'Write down bluff claims, soft confirmations, token reminders, or anything else you want to track.',
    viewHistory: 'View History',
    revealAlignment: 'Reveal Alignment',
    selectPlayerForAlignmentReveal: 'Choose a player to show an alignment to.',
    chooseAlignmentToShow: 'Choose what alignment to show {player}.',
    yourAlignmentIs: 'Your alignment is',
    youAreGood: "You're good",
    youAreEvil: "You're evil",

    // Shared narrator keys
    narratorSetup: 'Storyteller Setup',
    selectTwoPlayers: 'Select 2 players to show',
    selectWhichRoleToShow: 'Select which role to reveal',
    showToPlayer: 'Show to Player',
    oneOfThemIsThe: 'One of them is the...',

    // Return device interstitial
    returnDeviceToNarrator: 'Return the device to the Storyteller',
    returnDeviceDescription: 'Please hand the device back before continuing.',
    returnDeviceReady: 'Storyteller Ready',

    // Role Revelation
    roleRevelation: 'Role Revelation',
    roleRevelationDescription: 'Tap each player to show them their role',
    tapToReveal: 'Tap to reveal',
    revealed: 'Revealed',
    startFirstNight: 'Start Night 1',
    skipRoleRevelation: 'Skip and reveal roles later',
    revealAllFirst: 'Reveal all roles before continuing',

    // Night Dashboard
    night: 'Night',
    nightDashboard: 'Night Actions',
    nightDashboardDescription: "Process each role's night action in order",
    nextAction: 'Next',
    actionDone: 'Done',
    actionSkipped: 'Skipped',
    actionPending: 'Pending',
    showActionAgain: 'Show again',
    actionReplayDescription:
      'Read-only replay of the recorded result for this action.',
    rerunSkippedAction: 'Run anyway',
    rerunSkippedActionWarning:
      'This action was skipped earlier. Running it now may affect the current game state.',
    minionInfo: 'Minion Info',
    minionInfoDescription:
      'Show this minion the evil team information they learn on the first night.',
    minionInfoSkippedUnderSeven:
      'Skipped because games with fewer than 7 players do not have minions and demons learn each other.',
    demonInfo: 'Demon Info',
    demonInfoDescription:
      'Show this demon the minions they learn on the first night.',
    demonInfoSkippedUnderSeven:
      'Skipped because games with fewer than 7 players do not have demons and minions learn each other.',
    demonBluffsDescription:
      'Choose and show the three bluff roles this demon can claim during the game.',
    demonCreationDeaths: 'Demon Creation Deaths',
    demonCreationDeathsDescription:
      'A Demon was created tonight. Choose any players who die tonight.',
    demonCreationDeathsConfirm: 'Confirm Night Deaths',
    allActionsComplete: 'All night actions have been processed',
    proceedToDay: 'Proceed to Day',
    undoLastDashboardStep: 'Return to Previous Step',
    undoLastDashboardStepTitle: 'Return to previous step?',
    undoLastDashboardStepDescription:
      'This will erase the last completed night dashboard step and any automatic effects, deaths, skips, or follow-ups it caused.',
    confirmUndoLastDashboardStep: 'Return',
    goodTwinLabel: 'Good Twin',
    evilTwinLabel: 'Evil Twin',

    // Night Steps
    nightSteps: 'Night Steps',
    stepConfigurePerceptions: 'Configure Perceptions',
    stepShowResult: 'Show Result',
    stepShowRole: 'Show Role',
    stepNarratorSetup: 'Storyteller Setup',
    stepChooseVictim: 'Choose Victim',
    stepChoosePlayer: 'Choose Player',
    stepSelectPlayer: 'Select Player',
    stepSelectPlayers: 'Select Players',
    stepAssignRedHerring: 'Assign Red Herring',
    stepSelectAndShow: 'Select & Show',
    stepChooseTarget: 'Choose Target',
    stepShowMinions: 'Show Minions',
    stepSelectBluffs: 'Select Bluffs',
    stepShowBluffs: 'Show Bluffs',
    stepSelectNewImp: 'Select New Imp',
    stepChooseMaster: 'Choose Master',
    stepViewGrimoire: 'View Grimoire',
    stepShowEvilTeam: 'Your Evil Team',
    noEvilTeammates: 'No evil teammates in play',

    // Malfunction Config
    stepConfigureMalfunction: 'Configure Malfunction',
    playerIsMalfunctioning:
      'This player is poisoned or drunk, so their ability malfunctions. As the Storyteller, choose what information they receive; it may be true or false.',
    chooseFalseNumber: 'What number should they see?',
    chooseFalseResult: 'What result should they see?',
    chooseFalseTarget: 'Which player should they be told is the role?',
    chooseFalseRole: 'What role should they see?',
    keepOriginalRole: 'Keep {role}',
    malfunctionWarning: 'Malfunctioning',
    falseInfoRequired: 'False Info Required',
    arbitraryInfoReminder:
      'This ability is poisoned or drunk, so the result can be arbitrary or unreliable. Choose what to show before waking the player.',
    falseInfoReminder:
      'Vortox is in play, so this Townsfolk ability must yield false information tonight. Choose the false result before waking the player.',

    // Setup Actions
    setupActions: 'Setup Actions',
    setupActionsSubtitle:
      'Configure roles that need storyteller setup before the game begins',
    allSetupActionsComplete: 'All setup actions complete',
    continueToRoleRevelation: 'Continue to Role Revelation',
    grimoireReviewSubtitle:
      'Review seat order and neighbors before preparing Night 1 information',
    grimoireReviewHint:
      'Tap a seat to inspect the circle before assigning bluffs, red herrings, or first-night info.',
    grimoireCircle: 'Seating Circle',
    grimoireViewCircle: 'Visual',
    grimoireViewList: 'Detail',
    grimoireSelectedSeat: 'Selected Seat',
    grimoireSeat: 'Seat {seat}',
    grimoireLeftNeighbor: 'Left neighbor',
    grimoireRightNeighbor: 'Right neighbor',
    grimoireReseatMode: 'Reseat',
    grimoireReseatHint:
      'Tap one seat, then another, to swap them. Changes update the live grimoire immediately.',
    grimoireReseatDone: 'Done Reseating',
    grimoireSwapPrompt: 'Swap {player} with...',
    continueToNightPrep: 'Continue to Setup',
    continueToNightActions: 'Continue to Night 1',
    nightPrepSummary: 'Prepared',
    nightPrepPending: 'Remaining',
    nightPrepRedHerring: 'Red Herring',
    nightPrepNoTarget: 'No target',
    nightPrepEvilPairs: '{count} evil pair(s)',

    // Perception Config
    perceptionConfigTitle: 'Configure Perceptions',
    perceptionConfigDescription:
      'Some players have abilities that cause them to register falsely. Before showing the result to the player, you must decide how these ambiguous players should be perceived for this specific ability.',
    howShouldRegister: 'How should {player} register?',
    registerAsGood: 'Good',
    registerAsEvil: 'Evil',
    actualRole: 'Actual: {role}',
    keepDefault: 'Default (no change)',
    keepOriginalTeam: '{team} (default)',

    // Dawn Screen
    dawnTitle: 'Dawn',
    dawnNoDeaths: 'No one died in the night',
    dawnDeathAnnouncement: '{player} has died',
    dawnDiedInTheNight: '{player} died in the night',
    continueToDay: 'Continue to Day',

    // Death Revelation
    deathRevealTitle: 'The Dead Rise',
    deathRevealSubtitle: 'A soul has been claimed...',
    deathRevealDead: 'Dead',
    deathRevealNextDeath: 'Next Death',
    deathRevealContinue: 'Continue',

    // Night Summary (on Day Phase)
    nightSummary: 'Round {round} Details',
    noDeathsLastNight: 'No one died last night',

    // Night Dashboard review
    actionSummary: 'Action Summary',
    noActionRecorded: 'No action recorded',

    // Role Revelation narrator hint
    roleRevelationNarratorHint:
      'Only you can see this screen. Tap a player, then hand the device to them to reveal their role.',

    // Nomination tracking
    alreadyNominated: 'Already nominated today',
    alreadyBeenNominated: 'Already been nominated today',

    // Hand device interstitial
    handDeviceTo: 'Hand the device to {player}',
    tapWhenReady: 'Tap when ready to show',

    // Audience indicators
    audienceNarrator: 'Storyteller',
    audiencePlayerChoice: 'Wake player',
    audiencePlayerReveal: 'Show to player',
    storytellerDecision: 'This is your decision as Storyteller',
    wakePlayerPrompt: 'Wake {player} and ask them to choose',
    skipNightAction: 'Skip night action',

    // Groups
    otherPlayers: 'Other Players',
    currentPlayer: 'Current player',
  },

  teams: {
    townsfolk: {
      name: 'Townsfolk',
      winCondition: 'Execute the Demon to win!',
    },
    outsider: {
      name: 'Outsider',
      winCondition:
        'Execute the Demon to win! But beware, your ability may hinder the town.',
    },
    minion: {
      name: 'Minion',
      winCondition:
        'Help your Demon survive! Evil wins when only 2 players remain alive and at least 1 is a Demon (or via special abilities).',
    },
    demon: {
      name: 'Demon',
      winCondition:
        'Stay hidden and eliminate the town. Evil wins when only 2 players remain alive (or via special abilities).',
    },
  },

  ui: {
    effects: 'Effects',
    seeRoleCard: 'See Role Card',
    editEffects: 'Edit Effects',
    editEffectConfig: 'Edit Effect',
    currentEffects: 'Current Effects',
    addEffect: 'Add Effect',
    noEffects: 'No effects',
    close: 'Close',
    narrator: 'Narrator',
    unknown: 'Unknown',
    unknownPlayer: '[Unknown Player]',
    unknownRole: '[Unknown Role]',
    unknownRoleId: 'Unknown role: {roleId}',
  },

  history: {
    noEventsYet: 'No events yet',
    gameStarted: 'Game started',
    nightBegins: 'Night {round} begins',
    sunRises: 'The sun rises...',
    diedInNight: '{player} has died in the night',
    dayBegins: 'Day {round} begins',
    learnedRole: '{player} learned they are the {role}',
    noActionTonight: '{role} has no action tonight',
    nominates: '{nominator} nominates {nominee}',
    voteResult: '{player}: {votes} votes ({threshold} needed). ',
    votePassed: '{player} goes on the block!',
    voteFailed: 'Not enough votes.',
    voteTied: 'Tied with {player} \u2014 block cleared.',
    executed: '{player} has been executed',
    goodWins: 'Good wins! The Demon has been defeated.',
    evilWins: 'Evil wins! The town has fallen.',
    effectAdded: 'Storyteller added {effect} to {player}',
    effectUpdated: 'Storyteller updated {effect} on {player}',
    effectRemoved: 'Storyteller removed {effect} from {player}',
    roleChanged: '{player} became the {role}',
    setupAction: 'Setup: {player} configured as {role}',
    reviewedGrimoire: 'Storyteller reviewed the Grimoire',
    reseatedPlayers: 'Storyteller changed the seating order',
  },

  scripts: {
    'trouble-brewing': 'Trouble Brewing',
    'sects-and-violets': 'Sects & Violets',
    custom: 'Create Custom Script',
    officialScripts: 'Official Scripts',
    scriptTools: 'Build & Import',
    savedScripts: 'Saved Scripts',
    betaTag: 'BETA',
    importScript: 'Import Script',
    importScriptSubtitle:
      'Paste botcscripts JSON or import from a URL, then validate support before saving',
    importScriptHelp:
      'Bring in a script from botcscripts-style JSON. Unsupported characters are rejected.',
    importPasteJson: 'Paste JSON',
    importFromUrl: 'From URL',
    importPasteJsonHelp:
      'Paste the full exported JSON array for the script you want to import.',
    importFromUrlHelp:
      'Paste a URL that returns botcscripts-style JSON for a script export.',
    importJsonPlaceholder:
      '[{"id":"_meta","name":"Catfishing","author":"Emily"}, {"id":"investigator"}]',
    importValidate: 'Validate Script',
    importValidating: 'Validating...',
    importNotSupported: 'Not Supported',
    importUnsupportedHelp:
      'This script includes characters Grimorium does not support yet.',
    importParseError: 'Could not parse that script import.',
    continueToWakeOrder: 'Continue to Wake Order',
    wakeOrderImportTitle: 'Review Imported Wake Order',
    wakeOrderCustomTitle: 'Save Custom Script',
    wakeOrderSubtitle:
      'Review the derived wake order, drag to reorder it, then save the script.',
    firstNightWakeOrder: 'First Night',
    otherNightWakeOrder: 'Other Nights',
    wakeOrderHint:
      'Drag rows to reorder them. Up and down buttons are available as a fallback.',
    resetWakeOrder: 'Reset',
    noWakeRoles: 'No roles wake during this phase.',
    reactiveWakeRoles: 'Reactive Wakes',
    reactiveWakeRolesHint:
      'These are conditional or follow-up wakes. They are visible for review, but are not part of the fixed ordered wake sheet.',
    conditionalWakeTag: 'Conditional',
    saveScript: 'Save Script',
    editWakeOrder: 'Edit wake order',
    scriptNameLabel: 'Script Name',
    scriptAuthorLabel: 'Author',
    scriptAuthorPlaceholder: 'Optional',
    byAuthor: 'by {author}',
    selectScript: 'Choose a Script',
    selectScriptSubtitle:
      'Select an edition to determine which roles are available',
    enforceDistribution: 'Standard role distribution',
    freeformSelection: 'Any roles, any distribution',
    // Generator presets
    generateRoles: 'Generate Roles',
    simple: 'Simple',
    simpleDescription: 'Straightforward roles, easy to learn',
    interesting: 'Interesting',
    interestingDescription: 'A balanced mix of complexity',
    chaotic: 'Chaotic',
    chaoticDescription: 'Maximum deception and surprises',
    chaos: 'Chaos',
    selectThisPool: 'Select',
    regenerate: 'Regenerate',
    orPickManually: 'or pick manually',
    generate: 'Generate',
    manual: 'Manual',
    useThisPool: 'Use This Pool',
    presetApplied: '{preset} applied',
    rolesSelected: '{count} roles selected',
  },

  howToPlay: {
    title: 'How To Play',
    part1Title: '1. What Is Blood on the Clocktower?',
    p1_nutshellTitle: 'The Game in a Nutshell',
    p1_nutshell1:
      'Blood on the Clocktower is a **social deduction game** for 5–20 players.',
    p1_nutshell2:
      'One player is the **Storyteller** (narrator) — everyone else is a **Townsfolk, Outsider, Minion, or Demon**.',
    p1_nutshell3:
      'The **Good team** (Townsfolk + Outsiders) tries to find and execute the **Demon**.',
    p1_nutshell4:
      'The **Evil team** (Demon + Minions) tries to kill enough players to win.',
    p1_nutshell5:
      'The game alternates between **Night** (abilities happen secretly) and **Day** (players discuss and vote).',
    p1_teamsTitle: 'Teams & Alignments',
    p1_teamTownsfolk:
      'You are on the **Good team**. You do not know who anyone else is, but you have a useful ability. Talk to people, share and combine your information, and trust your instincts to find the Demon.',
    p1_teamTownsfolkExample: 'For example, the **Washerwoman** is a Townsfolk:',
    p1_teamOutsider:
      'You are on the **Good team**, but your ability is a burden. You might have false information, or your mere presence might make things harder for the town. You must overcome your handicap to help good win.',
    p1_teamOutsiderExample: 'For example, the **Drunk** is an Outsider:',
    p1_teamMinion:
      'You are on the **Evil team**. You know who the Demon is, and your goal is to protect them at all costs. Use your disruptive abilities to cause chaos, spread misinformation, and cast suspicion away from your Demon.',
    p1_teamMinionExample: 'For example, the **Poisoner** is a Minion:',
    p1_teamDemon:
      'You are the leader of the **Evil team**. You kill players in the night and know who your Minions are. To win, you must survive until the end by bluffing as a good character and throwing the town off your scent.',
    p1_teamDemonExample: 'For example, the **Imp** is a Demon:',
    p1_roundTitle: 'How a Round Works',
    p1_roundNight:
      'Players "wake up" one at a time (the Storyteller handles this). Information roles learn things, the Demon kills someone, etc.',
    p1_roundDay:
      'The Storyteller announces who died overnight. Players discuss, accuse, and try to figure out who is evil.',
    p1_roundNominate:
      'Any player can nominate another for execution. If the vote passes, that player is executed (and may die).',
    p1_roundWinGood: 'Good wins when the **Demon is executed**.',
    p1_roundWinEvil:
      'Evil wins when **only 2 players remain alive** (or through special abilities).',
    p1_roundWinConditions: 'Win Conditions',
    p1_roundNightLabel: 'Night',
    p1_roundDayLabel: 'Day',
    p1_roundNominateLabel: 'Nominations',
    p1_conceptsTitle: 'Key Concepts',
    p1_conceptPoison:
      "**Poisoning** — A poisoned player's ability malfunctions. Any information they receive is chosen by the Storyteller and may be true or false. They don't know they're poisoned.",
    p1_conceptDrunk:
      "**Drunkenness** — Like poisoning, but permanent. The Drunk thinks they're a different role, and any information they receive may be true or false.",
    p1_conceptDead:
      '**Dead players** — Dead players can still talk, debate, and vote **once** (then they lose their vote forever).',
    p1_conceptStoryteller:
      "**The Storyteller's role** — The Storyteller knows everything and runs the game. Grimorium IS the Storyteller's tool.",

    part2Title: '2. How To Use Grimorium',
    p2_createTitle: 'Creating a Game',
    p2_create1:
      '**Add Players** — Enter player names (the Storyteller is not a player).',
    p2_create2:
      '**Choose a Script** — A curated set of characters for a specific game complexity.',
    p2_create3:
      '**Select Roles** — Pick which roles are in the game, or let the app auto-generate a balanced set.',
    p2_create4: '**Assign Roles** — Drag/shuffle who gets which role.',
    p2_createTip:
      'The app enforces the correct team composition automatically based on your player count.',
    p2_setupTitle: 'Setup Actions',
    p2_setup1:
      'Some roles require the Storyteller to make a decision **before** the game begins.',
    p2_setup2:
      'For example, choosing which Townsfolk role the Drunk believes they are. The app guides you through each setup action automatically.',
    p2_revealTitle: 'Role Revelation',
    p2_reveal1:
      'The Storyteller shows each player their role privately using **themed role cards**.',
    p2_reveal2:
      'Each card shows: the role name, ability description, alignment, and win condition.',
    p2_reveal3:
      '**The Storyteller controls the device at all times** — show the screen to each player, then dismiss.',
    p2_revealWarning:
      'Grimorium is a **Storyteller-only tool**. The device never gets passed around.',
    p2_nightTitle: 'Night Phase',
    p2_night1:
      'The **Night Dashboard** shows every role that needs to act, in the correct wake order.',
    p2_night2: 'Tap a role to start its night action.',
    p2_night3:
      'For **information roles**: the app auto-calculates the correct information, accounting for poisoning and drunkenness.',
    p2_night4:
      'For **action roles**: select targets via an intuitive player list.',
    p2_night5:
      'The app handles all timing, status effects, and expiration automatically.',
    p2_nightTip:
      'If a role is **malfunctioning**, the app prompts you to provide false information.',
    p2_dayTitle: 'Dawn & Day Phase',
    p2_day1: '**Dawn:** The app announces overnight deaths.',
    p2_day2: '**Day Phase:** Players discuss.',
    p2_day3:
      'You can open the **Grimoire** for a status overview of all players.',
    p2_day4:
      'You can trigger **Day Actions** (e.g., Slayer shot) or start **Nominations**.',
    p2_voteTitle: 'Nominations & Voting',
    p2_vote1: 'Tap "Nominations" and select who nominates whom.',
    p2_vote2: 'Use the voting interface to track votes for and against.',
    p2_vote3: 'If the vote reaches majority, the player is **executed**.',
    p2_vote4:
      'Special interactions (like the Virgin) are handled automatically.',
    p2_endTitle: 'End of Day & Win Detection',
    p2_end1: 'End the day to transition to the next night.',
    p2_end2: 'The app continuously checks win conditions.',
    p2_end3: 'Demon executed → **Good wins**',
    p2_end4: 'Only 2 players alive → **Evil wins**',
    p2_end5: 'When a win is detected, the game ends with a Game Over screen.',
    p2_grimTitle: 'The Grimoire',
    p2_grim1: "The Storyteller's reference panel — accessible at any time.",
    p2_grim2:
      "See every player's **true role**, alive/dead status, and active effects.",
    p2_grim3:
      "**Manually add/remove effects** for edge cases the app can't predict.",
    p2_historyTitle: 'History Log',
    p2_history1: 'Every action in the game is recorded.',
    p2_history2:
      'Includes night actions, deaths, votes, executions, and effect changes.',
    p2_history3: 'Useful for catching mistakes or reviewing the game state.',

    part3Title: '3. Tips for Players',
    p3_tip1Title: 'Keep your secrets',
    p3_tip1Desc:
      'If you are good, be careful who you trust with your information. If you are evil, lie about who your character is and what they do!',
    p3_tip2Title: 'Talk to people privately',
    p3_tip2Desc:
      "Don't only have public conversations in the town square. Take players aside for 1-on-1 private chats to share information discreetly.",
    p3_tip3Title: 'Bluff!',
    p3_tip3Desc:
      "It is highly encouraged to bluff as a different role, even if you are on the good team. This makes the Demon's job much harder.",
    p3_tip4Title: 'Death is not the end',
    p3_tip4Desc:
      'In Blood on the Clocktower, dead players continue to play! You still close your eyes at night, you still talk during the day, and you get **one final vote** to use when it counts most.',

    part4Title: '4. Tips for Storytellers',
    p4_firstTitle: 'For First-Time Storytellers',
    p4_first1: "Start with **Trouble Brewing** — it's designed for learning.",
    p4_first2:
      'For your first game, try 5–8 players to keep things manageable.',
    p4_first3:
      "Use the auto-generate feature for role selection until you're comfortable picking roles yourself.",
    p4_first4:
      "Don't worry about memorizing role interactions — the app handles the complex mechanics.",
    p4_duringTitle: 'During the Game',
    p4_during1:
      "**Night:** Trust the wake order. The app knows when to skip roles that shouldn't wake.",
    p4_during2:
      '**Day:** Let players talk. Your job is to facilitate, not control the discussion.',
    p4_during3:
      '**Grimoire:** Check it whenever you need a reminder of who has what status.',
    p4_during4:
      '**History:** If players argue about what happened, the history log is the source of truth.',
    p4_pitfallsTitle: 'Common Pitfalls',
    p4_pitfalls1:
      "❌ Don't show your screen to players unless it's their role reveal or you're deliberately showing them information.",
    p4_pitfalls2:
      "❌ Don't forget that dead players get one final vote — the app tracks this, but remind players.",
    p4_pitfalls3:
      "❌ Don't stress about misinformation from malfunctioning roles — the app will prompt you to provide false info.",
    p4_pitfalls4:
      '✅ Use the "Skip" option when a role doesn\'t need to act (the app supports this).',
  },
}

export default en
