import { Translations } from '../types'

const es: Translations = {
  common: {
    continue: 'Continuar',
    confirm: 'Confirmar',
    cancel: 'Cancelar',
    back: 'Volver',
    next: 'Siguiente',
    players: 'Jugadores',
    player: 'Jugador',
    roles: 'Roles',
    role: 'Rol',
    random: 'Aleatorio',
    startGame: 'Iniciar Partida',
    mainMenu: 'Menú Principal',
    history: 'Historial',
    notes: 'Notas',
    winCondition: 'Condición de Victoria',
    youAreThe: 'Eres el/la...',
    iUnderstandMyRole: 'Entiendo mi rol',
  },

  mainMenu: {
    title: 'Grimorium',
    subtitle: 'Todo Cuentacuentos necesita un Grimorio',
    tapToOpen: 'Toca para abrir',
    continueGame: 'Continuar Partida',
    newGame: 'Nueva Partida',
    startFreshGame: 'Comenzar una nueva partida',
    rolesLibrary: 'Biblioteca de Roles',
    browseAllRoles: 'Explorar todas las cartas de rol',
    previousGames: 'Partidas Anteriores',
    completed: 'Completada',
    settingUp: 'Configurando',
    round: 'Ronda',
    language: 'Idioma',
  },

  newGame: {
    step1Title: 'Nueva Partida',
    step1Subtitle: 'Paso 1: Elegir cantidad de jugadores',
    addPlayer: 'Añadir Jugador',
    playerPlaceholder: 'Jugador',
    playerCountLabel: 'Total de Jugadores',
    playerCountHelp:
      'Elige cuántos jugadores participan en la partida. El Narrador no está incluido.',
    recommendedSplit: 'Distribución Recomendada',
    seatsAutoGenerated:
      'Por ahora se generan etiquetas de asiento automáticamente y se pueden refinar más adelante.',
    roleDrawTitle: 'Repartir Roles',
    roleDrawSubtitle:
      'Paso 3: Revela un rol aleatorio y guarda el nombre de cada jugador',
    roleDrawHelp:
      'Pasa el dispositivo por la mesa. Cada jugador toca una carta, ve su rol en privado y luego escribe su nombre para fijarlo.',
    rolesDealtLabel: 'roles repartidos',
    regenerateDeck: 'Regenerar',
    tapToRevealRole: 'Toca para revelar',
    drunkSetupTitle: 'Configuracion del Borracho',
    drunkSetupSubtitle:
      'Elige el Aldeano que cree ser antes de que ningun jugador revele',
    drunkSetupDescription:
      'Esta bolsa incluye al Borracho. Elige que personaje de Aldeano debe creer que es y luego continua con el flujo normal de revelacion.',
    chooseBelievedRole: 'Elige el rol de Aldeano que cree ser',
    playerNameLabel: 'Nombre del Jugador',
    playerNamePlaceholder: 'Escribe el nombre del jugador',
    lockRoleAndName: 'Guardar rol y nombre',
    roleLockedLabel: 'Rol fijado',
    minPlayersWarning: 'Añade al menos 5 jugadores para continuar',
    nextSelectRoles: 'Siguiente: Seleccionar Roles',
    loadedFromLastGame: 'De la última partida',

    step2Title: 'Nueva Partida',
    step2Subtitle: 'Paso 2: Seleccionar roles en juego',
    needAtLeastRoles: 'Se necesitan al menos {count} roles',
    needAtLeastImp: 'Se necesita al menos 1 Imp',
    needAtLeastDemon: 'Se necesita al menos 1 Demonio',
    nextAssignRoles: 'Siguiente: Asignar Roles',
    suggested: 'Sugerido',

    step3Title: 'Nueva Partida',
    step3Subtitle: 'Paso 3: Asignar roles (opcional)',
    assignmentInfo:
      'Opcionalmente asigna roles específicos a jugadores. Los jugadores sin asignar reciben roles aleatorios.',
    resetToRandom: 'Restablecer todo a aleatorio',
    playerAssignments: 'Asignaciones de Jugadores',
    randomPool: 'Pool Aleatorio',
    rolesForPlayers: '{roles} roles para {players} jugadores',
    impNotAssignedWarning:
      '¡El Imp no será asignado! Asegúrate de que al menos un jugador reciba el Imp o deja algunos jugadores en aleatorio.',
    demonNotAssignedWarning:
      '¡No se asignará ningún Demonio! Asegúrate de que al menos un jugador reciba un Demonio o deja algunos jugadores en aleatorio.',
    rolesRandomlyAssigned: 'Los roles se asignarán aleatoriamente',
    customizeAssignments: 'Personalizar Asignaciones',
    tapToAssign: 'Toca un jugador para asignar un rol específico',
  },

  game: {
    narratorGiveDevice: 'Dale el dispositivo a {player} para que vea su rol.',
    narratorWakePlayer:
      'Despierta a {player} ({role}) para su acción nocturna.',
    narratorRoleChanged: 'Dale el dispositivo a {player} — su rol ha cambiado.',
    readyShowToPlayer: 'Listo - Mostrar al Jugador',
    yourRoleHasChanged: '¡Tu rol ha cambiado!',
    yourGoodTwinIs: 'Tu gemelo bueno es...',
    yourEvilTwinIs: 'Tu gemelo malvado es...',

    nightComplete: 'Noche {round} Completa',
    nightActionsResolved:
      'Todas las acciones nocturnas han sido resueltas. ¿Listos para comenzar el día?',
    startDay: 'Comenzar Día',
    choosePlayerToKill: 'Elige un jugador para matar',
    selectVictim: 'Despierta a {player} y pídele que señale a su víctima.',
    confirmKill: 'Confirmar Asesinato',

    grimoire: 'Grimorio',
    daytimeActions: 'Acciones de Día',
    accusePlayerDescription: 'Acusa a un jugador y ponlo a votación',

    nominatesForExecution: '{nominator} nomina a {nominee} para ejecución',
    nominatesVerb: 'nomina a',
    forExecution: 'para ejecución',

    day: 'Día',
    discussionAndNominations: 'Discusión y nominaciones',
    alivePlayersLabel: 'Vivos',
    blockThresholdLabel: 'Para bloquear',
    newNomination: 'Nueva Nominación',
    whoIsNominating: '¿Quién está nominando?',
    whoAreTheyNominating: '¿A quién están nominando?',
    selectNominator: 'Seleccionar nominador...',
    selectNominee: 'Seleccionar nominado...',
    startNomination: 'Iniciar Nominación',

    executePlayer: 'Votar sobre {player}',
    votesNeeded: '{count} votos necesarios',
    votesCount: 'Votos',
    voteThreshold: 'de {threshold} necesarios',
    voteAction: 'Votar',
    dontVote: 'No Votar',
    goesOnBlock: '¡{player} está en la cuerda floja!',
    notEnoughVotes: 'No hay suficientes votos',
    tiedNoExecution: 'Empate \u2014 sin ejecución',
    currentBlock: '{player} en la cuerda floja ({count} votos)',
    needMoreThan: 'Se necesitan más de {count} para reemplazar',
    noOneOnBlock: 'Nadie en la cuerda floja',
    endDayExecute: 'Terminar Día \u2014 Ejecutar a {player}',
    endDayNoExecution: 'Terminar Día \u2014 Sin Ejecución',
    confirmVotes: 'Confirmar Votos',
    cancelNomination: 'Cancelar Nominación',
    nominee: 'Nominado/a',
    ghostVoteAvailable: 'Voto fantasma disponible',
    ghostVoteSpent: 'Voto fantasma usado',
    cannotVote: 'No puede votar',
    butlerCannotVote: 'No puede votar a menos que el amo vote',
    butlerDeadWarning: 'La regla del amo no aplica estando muerto',

    // Slayer
    slayerAction: 'Disparo del Matador',
    slayerActionDescription: 'Proclama ser el Matador y dispara a un jugador',
    selectSlayer: 'Seleccionar Matador',
    selectTarget: 'Seleccionar Objetivo',
    confirmSlayerShot: 'Confirmar Disparo',

    goodWins: '¡Gana el Bien!',
    evilWins: '¡Gana el Mal!',
    townVanquishedDemon: '¡El pueblo ha vencido al Demonio!',
    demonConqueredTown: '¡El Demonio ha conquistado el pueblo!',
    winTriggeredBy: 'Disparador de Victoria',
    winReasonAllDemonsDead: 'Todos los Demonios están muertos.',
    winReasonFinalTwoAlive:
      'Solo quedan 2 jugadores con vida y al menos 1 es un Demonio.',
    winReasonVortoxNoExecution:
      'Regla de Vortox: no hubo ejecución hoy.',
    winReasonMartyrdomExecution:
      'Una ejecución activó una condición de victoria malvada tipo martirio.',
    winReasonEvilTwinGoodExecuted:
      'Se ejecutó al Gemelo Bueno.',
    winReasonEvilTwinEvilExecuted:
      'Se ejecutó al Gemelo Malvado.',
    winReasonMayorPeacefulVictory:
      'Se cumplió la condición de victoria pacífica del Alcalde.',
    winReasonSpecialAbility:
      'Se cumplió una condición de victoria por habilidad especial.',
    winReasonSourceRole: 'Rol origen: {role}',
    winReasonSourceEffect: 'Efecto origen: {effect}',
    finalRoles: 'Roles Finales',
    backToMainMenu: 'Volver al Menú Principal',

    gameHistory: 'Historial de Partida',
    storytellerMenu: 'Menú del Cuentacuentos',
    showGrimoire: 'Mostrar Grimorio',
    showAllCharacters: 'Mostrar Todos los Personajes',
    takeNotes: 'Tomar Notas',
    storytellerNotes: 'Notas del Cuentacuentos',
    storytellerNotesDescription:
      'Guarda recordatorios rápidos, afirmaciones y sospechas mientras diriges la partida.',
    storytellerNotesPlaceholder:
      'Escribe faroles, confirmaciones suaves, recordatorios de fichas o cualquier otra cosa que quieras seguir.',
    viewHistory: 'Ver Historial',
    revealAlignment: 'Revelar alineación',
    selectPlayerForAlignmentReveal:
      'Elige un jugador al que mostrar una alineación.',
    chooseAlignmentToShow:
      'Elige qué alineación mostrar a {player}.',
    yourAlignmentIs: 'Tu alineación es',
    youAreGood: 'Eres bueno',
    youAreEvil: 'Eres malvado',

    // Shared narrator keys
    narratorSetup: 'Configuración del Cuentacuentos',
    selectTwoPlayers: 'Selecciona 2 jugadores para mostrar',
    selectWhichRoleToShow: 'Selecciona qué rol revelar',
    showToPlayer: 'Mostrar al Jugador',
    oneOfThemIsThe: 'Uno de ellos es el/la...',

    // Return device interstitial
    returnDeviceToNarrator: 'Devuelve el dispositivo al Cuentacuentos',
    returnDeviceDescription:
      'Por favor, devuelve el dispositivo antes de continuar.',
    returnDeviceReady: 'Cuentacuentos Listo',

    // Role Revelation
    roleRevelation: 'Revelación de Roles',
    roleRevelationDescription: 'Toca cada jugador para mostrarle su rol',
    tapToReveal: 'Toca para revelar',
    revealed: 'Revelado',
    startFirstNight: 'Comenzar Noche 1',
    skipRoleRevelation: 'Omitir y revelar roles después',
    revealAllFirst: 'Revela todos los roles antes de continuar',

    // Night Dashboard
    night: 'Noche',
    nightDashboard: 'Acciones Nocturnas',
    nightDashboardDescription:
      'Procesa la acción nocturna de cada rol en orden',
    nextAction: 'Siguiente',
    actionDone: 'Hecho',
    actionSkipped: 'Omitido',
    actionPending: 'Pendiente',
    showActionAgain: 'Mostrar de nuevo',
    actionReplayDescription:
      'Repetición de solo lectura del resultado registrado para esta acción.',
    rerunSkippedAction: 'Ejecutar de todos modos',
    rerunSkippedActionWarning:
      'Esta acción se omitió antes. Ejecutarla ahora puede afectar el estado actual de la partida.',
    minionInfo: 'Información de Secuaces',
    minionInfoDescription:
      'Muestra a este Secuaz la información del equipo malvado que aprende en la primera noche.',
    minionInfoSkippedUnderSeven:
      'Se omitió porque en partidas con menos de 7 jugadores los Secuaces y el Demonio no se conocen entre sí.',
    demonInfo: 'Información del Demonio',
    demonInfoDescription:
      'Muestra a este Demonio los Secuaces que aprende en la primera noche.',
    demonInfoSkippedUnderSeven:
      'Se omitió porque en partidas con menos de 7 jugadores el Demonio y los Secuaces no se conocen entre sí.',
    demonBluffsDescription:
      'Elige y muestra los tres faroles que este Demonio puede reclamar durante la partida.',
    demonCreationDeaths: 'Muertes por Creación de Demonio',
    demonCreationDeathsDescription:
      'Se creó un Demonio esta noche. Elige qué jugadores mueren esta noche.',
    demonCreationDeathsConfirm: 'Confirmar Muertes Nocturnas',
    allActionsComplete: 'Todas las acciones nocturnas han sido procesadas',
    proceedToDay: 'Proceder al Día',
    undoLastDashboardStep: 'Volver al Paso Anterior',
    undoLastDashboardStepTitle: '¿Volver al paso anterior?',
    undoLastDashboardStepDescription:
      'Esto borrará el último paso completado del panel nocturno y cualquier efecto, muerte, omisión o seguimiento automático que haya causado.',
    confirmUndoLastDashboardStep: 'Volver',
    goodTwinLabel: 'Gemelo Bueno',
    evilTwinLabel: 'Gemelo Malvado',

    // Night Steps
    nightSteps: 'Pasos Nocturnos',
    stepConfigurePerceptions: 'Configurar Percepciones',
    stepShowResult: 'Mostrar Resultado',
    stepShowRole: 'Mostrar Rol',
    stepNarratorSetup: 'Configuración del Cuentacuentos',
    stepChooseVictim: 'Elegir Víctima',
    stepChoosePlayer: 'Elegir Jugador',
    stepSelectPlayer: 'Seleccionar Jugador',
    stepSelectPlayers: 'Seleccionar Jugadores',
    stepAssignRedHerring: 'Asignar Pista Falsa',
    stepSelectAndShow: 'Seleccionar y Mostrar',
    stepChooseTarget: 'Elegir Objetivo',
    stepShowMinions: 'Mostrar Secuaces',
    stepSelectBluffs: 'Seleccionar Faroles',
    stepShowBluffs: 'Mostrar Faroles',
    stepSelectNewImp: 'Seleccionar Nuevo Imp',
    stepChooseMaster: 'Elegir Amo',
    stepViewGrimoire: 'Ver Grimorio',
    stepShowEvilTeam: 'Tu Equipo Malvado',
    noEvilTeammates: 'No hay compañeros malvados en juego',

    // Malfunction Config
    stepConfigureMalfunction: 'Configurar Mal Funcionamiento',
    playerIsMalfunctioning:
      'Este jugador está envenenado o borracho, por lo que su habilidad falla. Como Cuentacuentos, elige qué información recibirá; puede ser verdadera o falsa.',
    chooseFalseNumber: '¿Qué número debería ver?',
    chooseFalseResult: '¿Qué resultado debería ver?',
    chooseFalseTarget: '¿A qué jugador le dirán que es el rol?',
    chooseFalseRole: '¿Qué rol debería ver?',
    keepOriginalRole: 'Mantener {role}',
    malfunctionWarning: 'Mal Funcionamiento',
    falseInfoRequired: 'Información Falsa Requerida',
    arbitraryInfoReminder:
      'Esta habilidad está envenenada o borracha, así que el resultado puede ser arbitrario o poco fiable. Elige qué mostrar antes de despertar al jugador.',
    falseInfoReminder:
      'Vortox está en juego, así que esta habilidad de Aldeanos debe dar información falsa esta noche. Elige el resultado falso antes de despertar al jugador.',

    // Setup Actions
    setupActions: 'Acciones de Configuración',
    setupActionsSubtitle:
      'Configura los roles que necesitan preparación del cuentacuentos antes de comenzar',
    allSetupActionsComplete: 'Todas las acciones de configuración completadas',
    continueToRoleRevelation: 'Continuar a Revelación de Roles',
    grimoireReviewSubtitle:
      'Revisa el orden de asientos y vecinos antes de preparar la información de la Noche 1',
    grimoireReviewHint:
      'Toca un asiento para inspeccionar el círculo antes de asignar faroles, pistas falsas o información de la primera noche.',
    grimoireCircle: 'Círculo de Asientos',
    grimoireViewCircle: 'Visual',
    grimoireViewList: 'Detalle',
    grimoireSelectedSeat: 'Asiento Seleccionado',
    grimoireSeat: 'Asiento {seat}',
    grimoireLeftNeighbor: 'Vecino izquierdo',
    grimoireRightNeighbor: 'Vecino derecho',
    grimoireReseatMode: 'Reubicar',
    grimoireReseatHint:
      'Toca un asiento y luego otro para intercambiarlos. Los cambios actualizan el grimorio al instante.',
    grimoireReseatDone: 'Terminar Reubicación',
    grimoireSwapPrompt: 'Intercambiar {player} con...',
    continueToNightPrep: 'Continuar a Configuración',
    continueToNightActions: 'Continuar a Noche 1',
    nightPrepSummary: 'Preparado',
    nightPrepPending: 'Pendiente',
    nightPrepRedHerring: 'Pista Falsa',
    nightPrepNoTarget: 'Sin objetivo',
    nightPrepEvilPairs: '{count} pareja(s) malvada(s)',

    // Perception Config
    perceptionConfigTitle: 'Configurar Percepciones',
    perceptionConfigDescription:
      'Algunos jugadores tienen habilidades que causan que se registren falsamente. Antes de mostrar el resultado al jugador, debes decidir cómo deben ser percibidos los jugadores ambiguos para esta habilidad específica.',
    howShouldRegister: '¿Cómo debe registrarse {player}?',
    registerAsGood: 'Bueno',
    registerAsEvil: 'Malvado',
    actualRole: 'Real: {role}',
    keepDefault: 'Por defecto (sin cambio)',
    keepOriginalTeam: '{team} (por defecto)',

    // Dawn Screen
    dawnTitle: 'Amanecer',
    dawnNoDeaths: 'Nadie murió en la noche',
    dawnDeathAnnouncement: '{player} ha muerto',
    dawnDiedInTheNight: '{player} ha muerto en la noche',
    continueToDay: 'Continuar al Día',

    // Night Summary (on Day Phase)
    nightSummary: 'Detalles de la Ronda {round}',
    noDeathsLastNight: 'Nadie murió anoche',

    // Death Revelation
    deathRevealTitle: 'Los Muertos se Alzan',
    deathRevealSubtitle: 'Un alma ha sido reclamada...',
    deathRevealDead: 'Muerto',
    deathRevealNextDeath: 'Siguiente Muerte',
    deathRevealContinue: 'Continuar',

    // Night Dashboard review
    actionSummary: 'Resumen de Acción',
    noActionRecorded: 'Sin acción registrada',

    // Role Revelation narrator hint
    roleRevelationNarratorHint:
      'Solo tú puedes ver esta pantalla. Toca un jugador, luego entrégale el dispositivo para revelar su rol.',

    // Nomination tracking
    alreadyNominated: 'Ya nominó hoy',
    alreadyBeenNominated: 'Ya fue nominado/a hoy',

    // Hand device interstitial
    handDeviceTo: 'Entrega el dispositivo a {player}',
    tapWhenReady: 'Toca cuando estés listo para mostrar',

    // Audience indicators
    audienceNarrator: 'Cuentacuentos',
    audiencePlayerChoice: 'Despertar jugador',
    audiencePlayerReveal: 'Mostrar al jugador',
    storytellerDecision: 'Esta es tu decisión como Cuentacuentos',
    wakePlayerPrompt: 'Despierta a {player} y pídele que elija',
    skipNightAction: 'Omitir acción nocturna',

    // Groups
    otherPlayers: 'Otros Jugadores',
    currentPlayer: 'Jugador actual',
  },

  teams: {
    townsfolk: {
      name: 'Aldeano',
      winCondition: '¡Ejecuta al Demonio para ganar!',
    },
    outsider: {
      name: 'Forastero',
      winCondition:
        '¡Ejecuta al Demonio para ganar! Pero cuidado, tu habilidad puede perjudicar al pueblo.',
    },
    minion: {
      name: 'Secuaz',
      winCondition:
        '¡Ayuda a tu Demonio a sobrevivir! El mal gana cuando solo quedan 2 jugadores con vida y al menos 1 es un Demonio (o por habilidades especiales).',
    },
    demon: {
      name: 'Demonio',
      winCondition:
        'Permanece oculto y elimina al pueblo. El mal gana cuando solo quedan 2 jugadores con vida (o por habilidades especiales).',
    },
  },

  ui: {
    effects: 'Efectos',
    seeRoleCard: 'Ver Carta de Rol',
    editEffects: 'Editar Efectos',
    editEffectConfig: 'Editar Efecto',
    currentEffects: 'Efectos Actuales',
    addEffect: 'Añadir Efecto',
    noEffects: 'Sin efectos',
    close: 'Cerrar',
    narrator: 'Cuentacuentos',
    unknown: 'Desconocido',
    unknownPlayer: '[Jugador Desconocido]',
    unknownRole: '[Rol Desconocido]',
    unknownRoleId: 'Rol desconocido: {roleId}',
  },

  history: {
    noEventsYet: 'Aún no hay eventos',
    gameStarted: 'Partida iniciada',
    nightBegins: 'Noche {round} comienza',
    sunRises: 'El sol sale...',
    diedInNight: '{player} ha muerto en la noche',
    dayBegins: 'Día {round} comienza',
    learnedRole: '{player} descubrió que es el/la {role}',
    noActionTonight: '{role} no tiene acción esta noche',
    nominates: '{nominator} nomina a {nominee}',
    voteResult: '{player}: {votes} votos ({threshold} necesarios). ',
    votePassed: '¡{player} está en la cuerda floja!',
    voteFailed: 'No hay suficientes votos.',
    voteTied: 'Empate con {player} \u2014 nadie en la cuerda floja.',
    executed: '{player} ha sido ejecutado/a',
    goodWins: '¡El Bien gana! El Demonio ha sido derrotado.',
    evilWins: '¡El Mal gana! El pueblo ha caído.',
    effectAdded: 'El Cuentacuentos añadió {effect} a {player}',
    effectUpdated: 'El Cuentacuentos actualizó {effect} en {player}',
    effectRemoved: 'El Cuentacuentos eliminó {effect} de {player}',
    roleChanged: '{player} se convirtió en el/la {role}',
    setupAction: 'Configuración: {player} configurado como {role}',
    reviewedGrimoire: 'El Cuentacuentos revisó el Grimorio',
    reseatedPlayers: 'El Cuentacuentos cambió el orden de los asientos',
  },

  scripts: {
    'trouble-brewing': 'Problemas en el Pueblo',
    'sects-and-violets': 'Sectas y Violetas',
    custom: 'Crear Guión Personalizado',
    officialScripts: 'Guiones Oficiales',
    scriptTools: 'Crear e Importar',
    savedScripts: 'Guiones Guardados',
    betaTag: 'BETA',
    importScript: 'Importar Guión',
    importScriptSubtitle:
      'Pega JSON de botcscripts o importa desde una URL y valida la compatibilidad antes de guardar',
    importScriptHelp:
      'Importa un guión desde JSON estilo botcscripts. Los personajes no compatibles se rechazan.',
    importPasteJson: 'Pegar JSON',
    importFromUrl: 'Desde URL',
    importPasteJsonHelp:
      'Pega el arreglo JSON completo exportado para el guión que quieres importar.',
    importFromUrlHelp:
      'Pega una URL que devuelva JSON estilo botcscripts para una exportación de guión.',
    importJsonPlaceholder:
      '[{"id":"_meta","name":"Catfishing","author":"Emily"}, {"id":"investigator"}]',
    importValidate: 'Validar Guión',
    importValidating: 'Validando...',
    importNotSupported: 'No Compatible',
    importUnsupportedHelp:
      'Este guión incluye personajes que Grimorium todavía no soporta.',
    importParseError: 'No se pudo interpretar la importación del guión.',
    continueToWakeOrder: 'Continuar al Orden Nocturno',
    wakeOrderImportTitle: 'Revisar Orden Importado',
    wakeOrderCustomTitle: 'Guardar Guión Personalizado',
    wakeOrderSubtitle:
      'Revisa el orden nocturno derivado, reordénalo arrastrando y luego guarda el guión.',
    firstNightWakeOrder: 'Primera Noche',
    otherNightWakeOrder: 'Otras Noches',
    wakeOrderHint:
      'Arrastra las filas para reordenarlas. Los botones de subir y bajar sirven como alternativa.',
    resetWakeOrder: 'Restablecer',
    noWakeRoles: 'Ningún rol despierta durante esta fase.',
    reactiveWakeRoles: 'Despertares Reactivos',
    reactiveWakeRolesHint:
      'Estos son despertares condicionales o de seguimiento. Se muestran para revisarlos, pero no forman parte del orden fijo nocturno.',
    conditionalWakeTag: 'Condicional',
    saveScript: 'Guardar Guión',
    editWakeOrder: 'Editar orden nocturno',
    scriptNameLabel: 'Nombre del Guión',
    scriptAuthorLabel: 'Autor',
    scriptAuthorPlaceholder: 'Opcional',
    byAuthor: 'por {author}',
    selectScript: 'Elige un Guión',
    selectScriptSubtitle:
      'Selecciona una edición para determinar los roles disponibles',
    enforceDistribution: 'Distribución estándar de roles',
    freeformSelection: 'Cualquier rol, cualquier distribución',
    // Generator presets
    generateRoles: 'Generar Roles',
    simple: 'Simple',
    simpleDescription: 'Roles sencillos, fáciles de aprender',
    interesting: 'Interesante',
    interestingDescription: 'Una mezcla equilibrada de complejidad',
    chaotic: 'Caótico',
    chaoticDescription: 'Máximo engaño y sorpresas',
    chaos: 'Caos',
    selectThisPool: 'Seleccionar',
    regenerate: 'Regenerar',
    orPickManually: 'o elige manualmente',
    generate: 'Generar',
    manual: 'Manual',
    useThisPool: 'Usar Este Pool',
    presetApplied: '{preset} aplicado',
    rolesSelected: '{count} roles seleccionados',
  },

  howToPlay: {
    title: 'Cómo Jugar',
    part1Title: '1. ¿Qué es Blood on the Clocktower?',
    p1_nutshellTitle: 'El Juego en Resumen',
    p1_nutshell1:
      'Blood on the Clocktower es un **juego de deducción social** para 5 a 20 jugadores.',
    p1_nutshell2:
      'Un jugador es el **Cuentacuentos** (narrador) — todos los demás son un **Aldeano, Forastero, Secuaz o Demonio**.',
    p1_nutshell3:
      'El **equipo del Bien** (Aldeanos + Forasteros) intenta encontrar y ejecutar al **Demonio**.',
    p1_nutshell4:
      'El **equipo del Mal** (Demonio + Secuaces) intenta matar a suficientes jugadores para ganar.',
    p1_nutshell5:
      'El juego alterna entre la **Noche** (las habilidades ocurren en secreto) y el **Día** (los jugadores discuten y votan).',
    p1_teamsTitle: 'Equipos y Alineaciones',
    p1_teamTownsfolk:
      'Estás en el **equipo del Bien**. No sabes quiénes son los demás, pero tienes una habilidad útil. Habla con la gente, comparte y combina tu información, y confía en tus instintos para encontrar al Demonio.',
    p1_teamTownsfolkExample: 'Por ejemplo, la **Lavandera** es un Aldeano:',
    p1_teamOutsider:
      'Estás en el **equipo del Bien**, pero tu habilidad es una carga. Podrías tener información falsa, o tu mera presencia podría dificultar las cosas para el pueblo. Debes superar tu desventaja para ayudar a ganar al bien.',
    p1_teamOutsiderExample: 'Por ejemplo, el **Borracho** es un Forastero:',
    p1_teamMinion:
      'Estás en el **equipo del Mal**. Sabes quién es el Demonio y tu objetivo es protegerlo a toda costa. Usa tus habilidades disruptivas para causar el caos, difundir desinformación y alejar las sospechas de tu Demonio.',
    p1_teamMinionExample: 'Por ejemplo, el **Envenenador** es un Secuaz:',
    p1_teamDemon:
      'Eres el líder del **equipo del Mal**. Matas a los jugadores por la noche y sabes quiénes son tus Secuaces. Para ganar, debes sobrevivir hasta el final fingiendo ser un personaje bueno y despistando al pueblo.',
    p1_teamDemonExample: 'Por ejemplo, el **Diablillo** es un Demonio:',
    p1_roundTitle: 'Cómo Funciona una Ronda',
    p1_roundNight:
      'Los jugadores "despiertan" uno a uno (controlado por el Cuentacuentos). Los roles de información aprenden cosas, el Demonio mata a alguien, etc.',
    p1_roundDay:
      'El Cuentacuentos anuncia quién murió durante la noche. Los jugadores discuten, acusan e intentan averiguar quién es malvado.',
    p1_roundNominate:
      'Cualquier jugador puede nominar a otro para ser ejecutado. Si el voto se aprueba, ese jugador es ejecutado (y puede morir).',
    p1_roundWinGood: 'El Bien gana cuando el **Demonio es ejecutado**.',
    p1_roundWinEvil:
      'El Mal gana cuando **solo quedan 2 jugadores vivos** (o mediante habilidades especiales).',
    p1_roundWinConditions: 'Condiciones de Victoria',
    p1_roundNightLabel: 'Noche',
    p1_roundDayLabel: 'Día',
    p1_roundNominateLabel: 'Nominaciones',
    p1_conceptsTitle: 'Conceptos Clave',
    p1_conceptPoison:
      '**Envenenamiento** — La habilidad de un jugador envenenado falla. Cualquier información que reciba la elige el Cuentacuentos y puede ser verdadera o falsa. El jugador no sabe que está envenenado.',
    p1_conceptDrunk:
      '**Ebriedad** — Como estar envenenado, pero permanente. El Borracho cree que tiene un rol distinto, y cualquier información que reciba puede ser verdadera o falsa.',
    p1_conceptDead:
      '**Jugadores muertos** — Los jugadores muertos aún pueden hablar, debatir y votar **una vez** (luego pierden su voto para siempre).',
    p1_conceptStoryteller:
      '**El rol del Cuentacuentos** — El Cuentacuentos sabe todo y dirige la partida. Grimorium ES la herramienta del Cuentacuentos.',

    part2Title: '2. Cómo Usar Grimorium',
    p2_createTitle: 'Crear una Partida',
    p2_create1:
      '**Añadir Jugadores** — Introduce los nombres (el Cuentacuentos no es un jugador).',
    p2_create2:
      '**Elegir un Guión** — Un conjunto selecto de personajes para una complejidad específica.',
    p2_create3:
      '**Seleccionar Roles** — Elige qué roles están en juego, o deja que la aplicación genere un grupo equilibrado.',
    p2_create4: '**Asignar Roles** — Arrastra o reparte quién obtiene qué rol.',
    p2_createTip:
      'La aplicación aplica la composición correcta del equipo automáticamente basada en el número de jugadores.',
    p2_setupTitle: 'Acciones de Configuración',
    p2_setup1:
      'Algunos roles requieren que el Cuentacuentos tome una decisión **antes** de que comience el juego.',
    p2_setup2:
      'Por ejemplo, elegir qué rol de Aldeano cree que es el Borracho. La aplicación te guía a través de la configuración.',
    p2_revealTitle: 'Revelación de Rol',
    p2_reveal1:
      'El Cuentacuentos muestra a cada jugador su rol en privado usando **cartas de rol temáticas**.',
    p2_reveal2:
      'Cada carta muestra: el nombre del rol, la descripción de la habilidad, la alineación y la condición de victoria.',
    p2_reveal3:
      '**El Cuentacuentos controla el dispositivo en todo momento** — muestra la pantalla a cada jugador y luego ocúltala.',
    p2_revealWarning:
      'Grimorium es una herramienta **solo para el Cuentacuentos**. El dispositivo nunca se pasa de mano en mano.',
    p2_nightTitle: 'Fase de Noche',
    p2_night1:
      'El **Panel Nocturno** muestra cada rol que necesita actuar, en el orden correcto.',
    p2_night2: 'Toca un rol para comenzar su acción nocturna.',
    p2_night3:
      'Para los **roles de información**: la app autocalcula la información correcta, considerando envenenamientos o ebriedad.',
    p2_night4:
      'Para los **roles de acción**: selecciona objetivos a través de una lista intuitiva.',
    p2_night5:
      'La aplicación maneja todos los tiempos, efectos de estado y caducidades automáticamente.',
    p2_nightTip:
      'Si un rol tiene un **mal funcionamiento**, la aplicación te pedirá que proporciones información falsa.',
    p2_dayTitle: 'Fase de Día y Amanecer',
    p2_day1: '**Amanecer:** La aplicación anuncia las muertes de la noche.',
    p2_day2: '**Fase de Día:** Los jugadores discuten.',
    p2_day3:
      'Puedes abrir el **Grimorio** para obtener un resumen del estado de los jugadores.',
    p2_day4:
      'Puedes activar las **Acciones de Día** (ej. disparo del Cazador de Demonios) o iniciar **Nominaciones**.',
    p2_voteTitle: 'Nominaciones y Votaciones',
    p2_vote1: 'Toca "Nominaciones" y selecciona quién nomina a quién.',
    p2_vote2:
      'Usa la interfaz de votación para hacer seguimiento de los votos a favor y en contra.',
    p2_vote3: 'Si la votación alcanza la mayoría, el jugador es **ejecutado**.',
    p2_vote4:
      'Las interacciones especiales (como la Virgen) se manejan de forma automática.',
    p2_endTitle: 'Fin del Día y Detección de Victoria',
    p2_end1: 'Termina el día para pasar a la siguiente noche.',
    p2_end2: 'La aplicación revisa constantemente las condiciones de victoria.',
    p2_end3: 'Demonio ejecutado → **Gana el Bien**',
    p2_end4: 'Solo quedan 2 jugadores vivos → **Gana el Mal**',
    p2_end5:
      'Cuando detecta victoria, la partida termina en la pantalla de Fin del Juego.',
    p2_grimTitle: 'El Grimorio',
    p2_grim1:
      'El panel de referencia del Cuentacuentos — accesible en cualquier momento.',
    p2_grim2:
      'Consulta el **rol verdadero** de cada jugador, estado vivo/muerto, y los efectos activos.',
    p2_grim3:
      '**Añade o retira efectos manualmente** en casos peculiares que la app no pueda predecir.',
    p2_historyTitle: 'Registro de Historial',
    p2_history1: 'Cada acción en la partida queda registrada.',
    p2_history2:
      'Incluye acciones nocturnas, muertes, votos, ejecuciones, y cambio de efectos.',
    p2_history3: 'Útil para solventar errores o revisar el estado del juego.',

    part3Title: '3. Consejos para Jugadores',
    p3_tip1Title: 'Guarda tus secretos',
    p3_tip1Desc:
      'Si eres bueno, ten cuidado en quién confías con tu información. Si eres malvado, ¡miente sobre quién eres y qué haces!',
    p3_tip2Title: 'Habla en privado',
    p3_tip2Desc:
      'No tengas solo conversaciones públicas con el grupo de jugadores. ¡Apártate con otros jugadores para tener charlas privadas 1 a 1!',
    p3_tip3Title: '¡Finge!',
    p3_tip3Desc:
      'Es altamente recomendado que pretendas ser otro personaje, o incluso otro bando. Esto hace el trabajo del demonio mucho más difícil.',
    p3_tip4Title: 'La muerte no es el final',
    p3_tip4Desc:
      'En Blood on the clocktower, ¡los jugadores muertos siguen jugando! Te puedes comunicar con vivos durante el día y tienes **un voto final** para usarlo cuando realmente importe.',

    part4Title: '4. Consejos para el Cuentacuentos',
    p4_firstTitle: 'Para la primera vez como Cuentacuentos',
    p4_first1:
      'Comienza jugando **Problemas en el Pueblo** — está diseñado para aprender.',
    p4_first2:
      'Para tu primera partida, intenta entre 5-8 jugadores para mantener el control de todo.',
    p4_first3:
      'Utiliza el generador automático de grupos de roles hasta que te sientas lo suficientemente cómodo.',
    p4_first4:
      'No te preocupes de memorizar las características especiales — ¡la app los controla y hace por tí!.',
    p4_duringTitle: 'Durante el Juego',
    p4_during1:
      '**Noche:** Confía en el orden para despertar jugadores. La aplicación avisará de los que no deban despertar.',
    p4_during2:
      '**Día:** Deja que los jugadores hablen e interactúen. Tu deber como Cuentacuentos es dirigir, pero no intervenir en discusiones ajenas.',
    p4_during3:
      '**Grimorio:** Puedes revisarlo repetidas veces de forma rápida si no tienes en mente algo de cada jugador o los efectos temporales.',
    p4_during4:
      '**Historial:** Si hay un error, el historial te devolverá una respuesta absoluta.',
    p4_pitfallsTitle: 'Errores Comunes',
    p4_pitfalls1:
      '❌ No compartas tu pantalla al resto de participantes, está todo para guiar explícitamente tú la partida.',
    p4_pitfalls2:
      '❌ No olvides de que los jugadores muertos pueden emitir un último voto, de todas formas el software lleva el conteo.',
    p4_pitfalls3:
      '❌ No te estreses con los roles de Desinformación — la aplicación te avisará para dar resultados falsos.',
    p4_pitfalls4:
      '✅ Usa el botón de Omitir sin miedo en aquellos roles que no sea necesaria acción la noche en curso.',
  },
}

export default es
